// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM-2gwy27nzEk-aj_MLIjsrtfXXT26bU0',
    appId: '1:133245287900:web:fc5b32a1fc730b8694e319',
    messagingSenderId: '133245287900',
    projectId: 'otpfireb-7785d',
    authDomain: 'otpfireb-7785d.firebaseapp.com',
    storageBucket: 'otpfireb-7785d.appspot.com',
    measurementId: 'G-SZ0FXG5YCP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZVgy3JecLydDEU92pngmc4BKYyWcXzKM',
    appId: '1:133245287900:android:831aed2b3e11474a94e319',
    messagingSenderId: '133245287900',
    projectId: 'otpfireb-7785d',
    storageBucket: 'otpfireb-7785d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKNdWF3QwY_ljuuM6QjSDqhEphXJ_4IN8',
    appId: '1:133245287900:ios:56f1e4f918d54f4794e319',
    messagingSenderId: '133245287900',
    projectId: 'otpfireb-7785d',
    storageBucket: 'otpfireb-7785d.appspot.com',
    iosBundleId: 'com.example.otpfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKNdWF3QwY_ljuuM6QjSDqhEphXJ_4IN8',
    appId: '1:133245287900:ios:54ef04d5cfad086f94e319',
    messagingSenderId: '133245287900',
    projectId: 'otpfireb-7785d',
    storageBucket: 'otpfireb-7785d.appspot.com',
    iosBundleId: 'com.example.otpfirebase.RunnerTests',
  );
}
