// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZv90xRjTwsmg_XfDAB6EYXPB8uFfE5AY',
    appId: '1:519688314911:web:f67ac8d21f1c09b797b52a',
    messagingSenderId: '519688314911',
    projectId: 'sathixh-coludstorage',
    authDomain: 'sathixh-coludstorage.firebaseapp.com',
    storageBucket: 'sathixh-coludstorage.appspot.com',
    measurementId: 'G-8PLYWZCK15',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvtWe18CdAVal3eLDo2QoOkLQDsJebZj0',
    appId: '1:519688314911:android:d680225294f51b7797b52a',
    messagingSenderId: '519688314911',
    projectId: 'sathixh-coludstorage',
    storageBucket: 'sathixh-coludstorage.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3kFilp5-tVH_WQ9UIRcxkp5H5OQbdGRo',
    appId: '1:519688314911:ios:99974cd4a571b9fc97b52a',
    messagingSenderId: '519688314911',
    projectId: 'sathixh-coludstorage',
    storageBucket: 'sathixh-coludstorage.appspot.com',
    iosBundleId: 'com.example.cloudstoragefirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3kFilp5-tVH_WQ9UIRcxkp5H5OQbdGRo',
    appId: '1:519688314911:ios:493ff0990be25c7797b52a',
    messagingSenderId: '519688314911',
    projectId: 'sathixh-coludstorage',
    storageBucket: 'sathixh-coludstorage.appspot.com',
    iosBundleId: 'com.example.cloudstoragefirebase.RunnerTests',
  );
}
