// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApGw24P2zPexNZkyYoh9DVekuRycnjcNQ',
    appId: '1:323919578749:web:1be414c30bf5a2744d1314',
    messagingSenderId: '323919578749',
    projectId: 'sathishfb-9f59c',
    authDomain: 'sathishfb-9f59c.firebaseapp.com',
    storageBucket: 'sathishfb-9f59c.appspot.com',
    measurementId: 'G-7EQB1PBF66',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi21t33eNldo8TtBzv_5dtouJxTIkSpKQ',
    appId: '1:323919578749:android:0671639507105a274d1314',
    messagingSenderId: '323919578749',
    projectId: 'sathishfb-9f59c',
    storageBucket: 'sathishfb-9f59c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd2QI7rjHt4qU3EPtX3JmA4Ru_r5IkDWE',
    appId: '1:323919578749:ios:4fc74470eaa1c4074d1314',
    messagingSenderId: '323919578749',
    projectId: 'sathishfb-9f59c',
    storageBucket: 'sathishfb-9f59c.appspot.com',
    androidClientId: '323919578749-0449mc9g2n48551cfpovjktkjna1ctok.apps.googleusercontent.com',
    iosClientId: '323919578749-5qh4iiju2qtm7im6khokckc1lmtl7nku.apps.googleusercontent.com',
    iosBundleId: 'com.example.otpfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd2QI7rjHt4qU3EPtX3JmA4Ru_r5IkDWE',
    appId: '1:323919578749:ios:731c212d986bd7934d1314',
    messagingSenderId: '323919578749',
    projectId: 'sathishfb-9f59c',
    storageBucket: 'sathishfb-9f59c.appspot.com',
    androidClientId: '323919578749-0449mc9g2n48551cfpovjktkjna1ctok.apps.googleusercontent.com',
    iosClientId: '323919578749-b6lo6c9v8mo1rnj99brip2jsd14unum7.apps.googleusercontent.com',
    iosBundleId: 'com.example.otpfirebase.RunnerTests',
  );
}
